# Generated by Django 2.1.1 on 2018-09-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carimage',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
