# Generated by Django 2.1.1 on 2018-09-24 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_car_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=50)),
                ('pickup', models.CharField(max_length=50)),
                ('pickupdatetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dropoff', models.CharField(max_length=50)),
                ('dropoffdatetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
            ],
        ),
    ]
